Add isNullish and isInstance type guards
justinlettau/ts-util-is pull request #20
Opened 2020-10-06 15:38 UTC by joshgummersall

These two type guards would both be helpful to me in a current project.

2020-10-06 17:54 UTC, justinlettau requested changes

2020-10-06 17:54 UTC, justinlettau commented on src/index.ts
> +export function isNullish(value: any): value is null | undefined {
@joshgummersall Might `isNil` be a more common name for this?

Reference https://lodash.com/docs/4.17.15#isNil

2020-10-07 16:32 UTC, justinlettau approved these changes

2020-10-07 16:33 UTC, merged

2020-10-07 17:08 UTC, joshgummersall commented
Thanks @justinlettau!